### ISSUE TITLE
Binary content shouldn't be replace

### ISSUE THREAD

**Issue by HugoPoi** [bfncs/string-replace-middleware#1]
This middleware break all binary content.

If your express serve binary files, `string-replace-middleware` will replace the binary content by an utf8 encoded content.

## Solutions
* Check the res content-type before applying (maybe add an option for that)
* Decode the binary , replace, reencode as binary ?

## Workaround
Can be avoided by loading the middleware only on specifics paths.

**Comment by carlo-quinonez** [comment]
I just submitted a PR #2 for this.
